### ISSUE TITLE
[ROADMAP] Batched Inference

### ISSUE THREAD

**Issue by benniekiss** [benniekiss/faster-whisper-onnx#1]
This issue will serve as tracking for the implementation of batched inference support where a user can supply multiple audio files and they will be processed in parallel. 

The goal is to refactor the following methods so that they support batches of audio. More methods may be added as it becomes apparent that they need refactoring. Refactored methods should be submitted via PR, with one method per PR.

### [transcribe.py](https://github.com/benniekiss/faster-whisper-onnx/blob/fbcf58bf984a309edab9d21e23bca872e1d5fe61/faster_whisper/transcribe.py)
- [ ] [WhisperModel.transcribe](https://github.com/benniekiss/faster-whisper-onnx/blob/fbcf58bf984a309edab9d21e23bca872e1d5fe61/faster_whisper/transcribe.py#L201)
- [ ] [WhisperModel.generate_segments](https://github.com/benniekiss/faster-whisper-onnx/blob/fbcf58bf984a309edab9d21e23bca872e1d5fe61/faster_whisper/transcribe.py#L497)
- [ ] [WhisperModel.encode](https://github.com/benniekiss/faster-whisper-onnx/blob/fbcf58bf984a309edab9d21e23bca872e1d5fe61/faster_whisper/transcribe.py#L833)
- [ ] [WhisperModel.generate_with_fallback](https://github.com/benniekiss/faster-whisper-onnx/blob/fbcf58bf984a309edab9d21e23bca872e1d5fe61/faster_whisper/transcribe.py#L843)
- [ ] [get_suppressed_tokens](https://github.com/benniekiss/faster-whisper-onnx/blob/fbcf58bf984a309edab9d21e23bca872e1d5fe61/faster_whisper/transcribe.py#L1231)

### [vad.py](https://github.com/benniekiss/faster-whisper-onnx/blob/fbcf58bf984a309edab9d21e23bca872e1d5fe61/faster_whisper/vad.py)
- [ ] [get_speech_timestamps](https://github.com/benniekiss/faster-whisper-onnx/blob/fbcf58bf984a309edab9d21e23bca872e1d5fe61/faster_whisper/vad.py#L37)
- [ ] [collect_chunks](https://github.com/benniekiss/faster-whisper-onnx/blob/fbcf58bf984a309edab9d21e23bca872e1d5fe61/faster_whisper/vad.py#L179)
- [ ] [SileroVADModel.__call__](https://github.com/benniekiss/faster-whisper-onnx/blob/fbcf58bf984a309edab9d21e23bca872e1d5fe61/faster_whisper/vad.py#L257)

### [feature_extractor.py](https://github.com/benniekiss/faster-whisper-onnx/blob/fbcf58bf984a309edab9d21e23bca872e1d5fe61/faster_whisper/feature_extractor.py)
- [ ] [FeatureExtractor.__call__](https://github.com/benniekiss/faster-whisper-onnx/blob/fbcf58bf984a309edab9d21e23bca872e1d5fe61/faster_whisper/feature_extractor.py#L145)

### [audio.py](https://github.com/benniekiss/faster-whisper-onnx/blob/fbcf58bf984a309edab9d21e23bca872e1d5fe61/faster_whisper/audio.py)
- [ ] [pad_or_trim](https://github.com/benniekiss/faster-whisper-onnx/blob/fbcf58bf984a309edab9d21e23bca872e1d5fe61/faster_whisper/audio.py#L107)
